" -----
" VIMRC
" -----
scriptencoding utf-8

" --- Plugins (vim-plug) ---

call plug#begin('~/.vim/plugged')

" Editor enhancements
Plug 'Lokaltog/vim-easymotion'
Plug 'townk/vim-autoclose'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-speeddating'
Plug 'junegunn/vim-easy-align',     { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] }
Plug 'junegunn/vim-peekaboo'
Plug 'markonm/traces.vim'
Plug 'sjl/gundo.vim'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'justinj/vim-react-snippets'

" UI
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'chriskempson/tomorrow-theme', { 'rtp': 'vim/' }
Plug 'itchyny/vim-cursorword'
Plug 'myusuf3/numbers.vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'luochen1990/rainbow'

" Git
Plug 'airblade/vim-gitgutter',      { 'branch': 'main' }
Plug 'tpope/vim-fugitive'
Plug 'mattn/webapi-vim' | Plug 'mattn/gist-vim'

" Linting
Plug 'w0rp/ale'

" Language & filetype
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-liquid'
Plug 'tpope/vim-jdaddy'
Plug 'jmcantrell/vim-virtualenv'
Plug 'rking/ag.vim'
Plug 'majutsushi/tagbar'

" Writing
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/vim-journal',        { 'for': 'journal' }
Plug 'jceb/vim-orgmode',            { 'for': 'org' }
Plug 'vim-scripts/utl.vim'

call plug#end()
filetype plugin indent on
syntax enable

" --- GUI ---

set guioptions-=r
set guioptions-=m
set guioptions-=L
set guioptions-=T
set number
set norelativenumber
set colorcolumn=81
set textwidth=80
set visualbell
set list listchars=tab:▸\ ,trail:·,extends:»,precedes:«
set cmdheight=1
set scrolloff=5

" --- Indentation ---

set expandtab
set tabstop=4
set shiftwidth=4
set nowrap
set smartindent
set autoindent
set nosmarttab

" --- Search ---

set incsearch
set hlsearch
set ignorecase

" --- Behaviors ---

set backspace=2
set whichwrap+=<,>,h,l,[,]
set report=0
let g:mapleader = ","
set foldmethod=indent
set nofoldenable
set foldlevel=1
au FileType org setlocal foldenable

augroup view
  autocmd BufWinLeave * silent! mkview
  autocmd BufWinEnter * silent! loadview
augroup END

" --- Backup & swap (disabled) ---

set nobackup
set nowritebackup
set noswapfile

" --- Style ---

set laststatus=2
set t_Co=256
if has('gui_running')
    set macligatures
    set guifont=DankMono-Regular:h17
    set transparency=15
    set blurradius=10
else
    set guifont=DejaVu\ Sans\ Mono\ 10
endif
colorscheme Tomorrow-Night-Eighties
let g:airline_theme='tomorrow'

" --- Mappings ---

" Change pwd to current file location
nnoremap ,cd :cd %:p:h<CR>:pwd<CR>

" Move visual block up/down
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Navigate lint errors
nnoremap <silent> <m-p> :lprevious<CR>
nnoremap <silent> <m-n> :lnext<CR>

" Edit/reload vimrc
if has("win32")
    nmap <leader>v :e $myvimrc
    nmap <leader>s :so $myvimrc
else
    nmap <leader>v :e $MYVIMRC
    nmap <leader>s :so $MYVIMRC
endif

" Format JSON in buffer/selection
map <Leader>n :%!python -m json.tool<CR>

" --- Filetypes ---

au BufNewFile,BufRead VagrantFile* set filetype=ruby
au BufNewFile,BufRead Dockerfile*  set filetype=dockerfile
au BufNewFile,BufRead *.journal    set filetype=journal
au BufNewFile,BufRead *.md         set filetype=markdown

set tags=./tags;/

" --- Plugin config: ALE ---

let g:ale_fixers = {
\    '*': ['remove_trailing_lines', 'trim_whitespace'],
\    'javascript': ['prettier'],
\    'css': ['prettier'],
\}
let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_use_global = 1
let g:ale_javascript_prettier_options = '--print-width 100 --tab-width 4 --single-quote --trailing-comma es5'
let g:ale_sign_error = '✖'
let g:ale_sign_warning = '!'
highlight ALEErrorSign ctermbg=NONE ctermfg=red guibg=NONE guifg=red
highlight ALEWarningSign ctermbg=NONE ctermfg=yellow guibg=NONE guifg=yellow

" --- Plugin config: Airline ---

let g:airline_left_sep = ' '
let g:airline_right_sep = ' '
let g:airline#extensions#ale#enabled = 1

" --- Plugin config: EasyAlign ---

vmap <Enter> <Plug>(EasyAlign)

" --- Plugin config: EasyMotion ---

let g:EasyMotion_do_mapping = 0
nmap s <Plug>(easymotion-bd-w)
nmap t <Plug>(easymotion-t2)
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)
let g:EasyMotion_startofline      = 0
let g:EasyMotion_smartcase        = 1
let g:EasyMotion_use_smartsign_us = 1

" --- Plugin config: Gist ---

let g:gist_clip_command            = 'xclip -selection clipboard'
let g:gist_detect_filetype         = 1
let g:gist_open_browser_after_post = 1
let g:gist_browser_command         = 'chrome %URL%'
let g:gist_show_privates           = 1
let g:gist_post_private            = 1

" --- Plugin config: GitGutter ---

let g:gitgutter_sign_added = '▍'
let g:gitgutter_sign_modified = '▍'
let g:gitgutter_sign_removed = '▍'
let g:gitgutter_sign_removed_first_line = '▍'
let g:gitgutter_sign_removed_above_and_below = '▍'
let g:gitgutter_sign_modified_removed = '▍'
highlight GitGutterAdd    guifg=#009900 ctermfg=2
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1

" --- Plugin config: Fugitive ---

nnoremap <leader>gs :Gstatus<cr>

" --- Plugin config: Tagbar ---

nnoremap <F8> :TagbarToggle<CR>

" --- Plugin config: Gundo ---

nnoremap <F5> :GundoToggle<CR>

" --- Plugin config: Rainbow ---

let g:rainbow_active = 1

" --- Plugin config: UltiSnips ---

let g:UltiSnipsExpandTrigger       = "<tab>"
let g:UltiSnipsJumpForwardTrigger  = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsEditSplit           = "vertical"
let g:ultisnips_python_style       = "google"

" --- Plugin config: Goyo (focus mode) ---

function! s:goyo_enter()
  NumbersDisable
  set nonumber
  set norelativenumber
  colorscheme Tomorrow
endfunction

function! s:goyo_leave()
  set number
  set norelativenumber
  NumbersEnable
  colorscheme Tomorrow-Night-Eighties
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
